In [1]:
import numpy as np
import robot_env
import random
from IPython.display import clear_output
import time

In [2]:
#inisialisasi hyperparameter
num_episodes = 1000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

epsilon = 1
max_epsilon = 1
min_epsilon = 0.01
epsilon_decay_rate = 0.1

#Membuat Environment
env = robot_env.initialize_env()

#menginisialisasi posisi robot pertama kali (row_start, row_end, env)
env = robot_env.initialize_position(0, 0, env)

#Membuat array yang berisikan action apa saja yang bisa diambil
actions = robot_env.action_space()
# kiri = 0, kanan = 1, atas = 2, bawah = 3

#Initiaslisasi Q-Table
q_table = np.zeros((env.size, actions.size))

#inisialisasi reward
#Reward :
#Empty = -1
#Fire = -10
#2 Harta = +25
#1 Harta = +10
reward_all_episode = []


In [3]:
def choose_action(epsilon, state):
    random_num = random.uniform(0, 1)
    if (random_num < epsilon):
        action = np.random.choice(actions, 1)[0]
        
    else:
        index_state = state[0] + (state[0]*3) + state[0]
        action = np.argmax(q_table[index_state, :])
       
    return action

def update_q_table( state, new_state):
    index_state = state[0] + (state[0]*3) + state[0]
    index_new_state = new_state[0] + (new_state[0]*3) + new_state[0]
    
    
    q_table[index_state, action] = q_table[index_state, action] + (learning_rate * (reward + (discount_rate * np.max(q_table[index_new_state, :]) - q_table[index_state, action])))

In [4]:
for episode in range(num_episodes):
    env = robot_env.initialize_env()
    env = robot_env.initialize_position(0, 0, env)
    state = (0,0)
    done = False
    rewards_current_episode = 0
    print(f"Episode {episode+1} / {num_episodes}")
    
    for step in range(max_steps_per_episode):
        #choose action  (epislon greedy)
        action = choose_action(epsilon, state)
        #take action and get reward and next state
        new_state, reward, done, env = robot_env.take_action(action, env, False)
        #Uncommend this code if you render the environment
#         clear_output(wait=True)
#         time.sleep(0.5)
        #update q table
        update_q_table(state, new_state)
        #change current state
        rewards_current_episode += reward 
        
        
        #check if already on termination state
        if done:
            break
        state = new_state
    
    # Exploration rate decay
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-epsilon_decay_rate*episode)
    
    #Add current episode reward to all episode reward
    reward_all_episode.append(rewards_current_episode)

Episode 1 / 1000
Episode 2 / 1000
Episode 3 / 1000
Episode 4 / 1000
Episode 5 / 1000
Episode 6 / 1000
Episode 7 / 1000
Episode 8 / 1000
Episode 9 / 1000
Episode 10 / 1000
Episode 11 / 1000
Episode 12 / 1000
Episode 13 / 1000
Episode 14 / 1000
Episode 15 / 1000
Episode 16 / 1000
Episode 17 / 1000
Episode 18 / 1000
Episode 19 / 1000
Episode 20 / 1000
Episode 21 / 1000
Episode 22 / 1000
Episode 23 / 1000
Episode 24 / 1000
Episode 25 / 1000
Episode 26 / 1000
Episode 27 / 1000
Episode 28 / 1000
Episode 29 / 1000
Episode 30 / 1000
Episode 31 / 1000
Episode 32 / 1000
Episode 33 / 1000
Episode 34 / 1000
Episode 35 / 1000
Episode 36 / 1000
Episode 37 / 1000
Episode 38 / 1000
Episode 39 / 1000
Episode 40 / 1000
Episode 41 / 1000
Episode 42 / 1000
Episode 43 / 1000
Episode 44 / 1000
Episode 45 / 1000
Episode 46 / 1000
Episode 47 / 1000
Episode 48 / 1000
Episode 49 / 1000
Episode 50 / 1000
Episode 51 / 1000
Episode 52 / 1000
Episode 53 / 1000
Episode 54 / 1000
Episode 55 / 1000
Episode 56 / 1000
E

In [5]:
print(q_table)

[[4.23522238e+01 6.33863229e-01 1.43664173e+02 1.54830095e+03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.18117868e+02 1.57430095e+03 3.67887020e+01 6.41087127e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.63970141e-01 2.23130959e+00 2.28871387e+01 1.79991092e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]]


In [6]:
epsilon

0.01

In [7]:
env

array([[  0.,   0.,   0.,   0.],
       [  0.,   1., -10.,   0.],
       [  0.,   0.,   0.,  10.]])